# Generated by Django 5.1.3 on 2024-11-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_purch',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
    ]
