# Generated by Django 5.1.3 on 2024-11-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0003_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_purch',
            field=models.DateField(null=True),
        ),
    ]
